services:
  db:
    container_name: gophkeeper_postgres
    image: postgres:latest
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gophkeeper
      - POSTGRES_USER=gophkeeper
      - POSTGRES_PASSWORD=gophkeeper
    ports:
      - '5432:5432'